# Generated by Django 3.1 on 2022-05-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_a_glance', models.TextField()),
                ('message_from_ceo', models.TextField()),
                ('company_profile', models.TextField()),
                ('our_concern', models.TextField()),
            ],
        ),
    ]
